name: Test Changed Files

on:
  [push]

env:
  GO_VERSION: ">=1.22"
  APP_NAME: dotenv-myvault
  GO_PLATFORMS: 'linux-amd64, linux-ppc64le, darwin-amd64, darwin-arm64, windows-amd64'

jobs:
  changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*_test.go
            **/*.go

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  run_tests:
    needs: [changed-files]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      fail-fast: false
      max-parallel: 4
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run test ${{ matrix.files }}
        run: |
          dir=$(dirname ${{ matrix.files }})
          go test -v ./$dir -run $(basename ${{ matrix.files }} _test.go)