name: Test Changed Files

on:
  pull_request:
    branches: [ main ]
  push:
    paths: [ '*.go' ]

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get changed test files
        id: changed-files
        run: |
          # Get list of changed test files
          CHANGED_TEST_FILES=$(git diff --name-only --diff-filter=d origin/main...HEAD | grep '_test\.go$' || true)
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_TEST_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate test matrix
        id: generate-matrix
        run: |
          TESTS=$(cat << EOF | jq -R -s -c 'split("\n")[:-1]'
          ${{ steps.changed-files.outputs.changed_files }}
          EOF
          )
          echo "matrix=$TESTS" >> $GITHUB_OUTPUT

  run-tests:
    needs: test
    if: ${{ fromJson(needs.test.outputs.matrix).matrix != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testfile: ${{ fromJson(needs.test.outputs.matrix).matrix }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run test ${{ matrix.testfile }}
        run: |
          dir=$(dirname ${{ matrix.testfile }})
          go test -v ./$dir -run $(basename ${{ matrix.testfile }} _test.go)